se) [ir967@log-1 Learning-to-See-in-the-Dark]$ srun -c1 --gres=gpu:1 -t0:10:00 --mem=3000  --pty /bin/bash
(base) [ir967@gpu-39 Learning-to-See-in-the-Dark]$ conda activate sid2
(sid2) [ir967@gpu-39 Learning-to-See-in-the-Dark]$ python train_Sony.py 
2020-11-08 02:23:22.976468: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-11-08 02:23:23.186134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:05:00.0
totalMemory: 22.38GiB freeMemory: 22.23GiB
2020-11-08 02:23:23.186312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2020-11-08 02:24:08.997376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-08 02:24:08.997506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2020-11-08 02:24:08.997533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2020-11-08 02:24:08.997688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21562 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:05:00.0, compute capability: 6.1)
loaded ./e1_result_Sony/model.ckpt
1 1 Loss=0.159 Time=6.170
1 2 Loss=0.246 Time=2.709
1 3 Loss=0.204 Time=2.376
1 4 Loss=0.209 Time=2.344
1 5 Loss=0.184 Time=2.371
3 1 Loss=0.175 Time=0.085
3 2 Loss=0.146 Time=0.109
3 3 Loss=0.147 Time=0.106
3 4 Loss=0.172 Time=2.293
3 5 Loss=0.172 Time=0.093
5 1 Loss=0.156 Time=0.093
5 2 Loss=0.153 Time=0.111
5 3 Loss=0.152 Time=0.109
5 4 Loss=0.156 Time=0.111
5 5 Loss=0.162 Time=0.085
6 1 Loss=0.159 Time=2.202
Traceback (most recent call last):
  File "train_Sony.py", line 203, in <module>
    scipy.misc.toimage(temp * 255, high=255, low=0, cmin=0, cmax=255).save(
AttributeError: 'module' object has no attribute 'toimage'
(sid2) [ir967@gpu-39 Learning-to-See-in-the-Dark]$ exit
exit
srun: error: gpu-39: task 0: Exited with exit code 1
srun: Terminating job step 13578091.0
(base) [ir967@log-1 Learning-to-See-in-the-Dark]$ conda activate sid2
(sid2) [ir967@log-1 Learning-to-See-in-the-Dark]$ pip install pillow
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pillow
  Downloading https://files.pythonhosted.org/packages/12/ad/61f8dfba88c4e56196bf6d056cdbba64dc9c5dfdfbc97d02e6472feed913/Pillow-6.2.2-cp27-cp27mu-manylinux1_x86_64.whl (2.1MB)
     |████████████████████████████████| 2.1MB 7.0MB/s 
Installing collected packages: pillow
Successfully installed pillow-6.2.2
(sid2) [ir967@log-1 Learning-to-See-in-the-Dark]$ conda search pillow
Loading channels: done
# Name                       Version           Build  Channel             
pillow                         4.2.1  py27h7cd2321_0  pkgs/main           
pillow                         4.2.1  py35h03abc04_0  pkgs/main           
pillow                         4.2.1  py36h9119f52_0  pkgs/main           
pillow                         4.3.0  py27h353bd0c_1  pkgs/main           
pillow                         4.3.0  py35h550890c_1  pkgs/main           
pillow                         4.3.0  py36h6f462bf_1  pkgs/main           
pillow                         5.0.0  py27h3deb7b8_0  pkgs/main           
pillow                         5.0.0  py35h3deb7b8_0  pkgs/main           
pillow                         6.1.0  py27h34e0f95_0  pkgs/main           
pillow                         6.1.0  py36h34e0f95_0  pkgs/main           
pillow                         6.1.0  py37h34e0f95_0  pkgs/main           
pillow                         6.2.0  py27h34e0f95_0  pkgs/main           
pillow                         6.2.0  py36h34e0f95_0  pkgs/main           
pillow                         6.2.0  py37h34e0f95_0  pkgs/main           
pillow                         6.2.1  py27h34e0f95_0  pkgs/main           
pillow                         6.2.1  py36h34e0f95_0  pkgs/main           
pillow                         6.2.1  py37h34e0f95_0  pkgs/main           
pillow                         6.2.1  py38h34e0f95_0  pkgs/main           
pillow                         8.0.0  py37h9a89aac_0  pkgs/main           
pillow                         8.0.0  py38h9a89aac_0  pkgs/main           
pillow                         8.0.1  py37he98fc37_0  pkgs/main           
pillow                         8.0.1  py38h9a89aac_0  pkgs/main           
pillow                         8.0.1  py38he98fc37_0  pkgs/main           
(sid2) [ir967@log-1 Learning-to-See-in-the-Dark]$ pip uninstall pillow
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Uninstalling Pillow-6.2.2:
  Would remove:
    /scratch/ir967/miniconda3/envs/sid2/lib/python2.7/site-packages/PIL/*
    /scratch/ir967/miniconda3/envs/sid2/lib/python2.7/site-packages/Pillow-6.2.2.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled Pillow-6.2.2
(sid2) [ir967@log-1 Learning-to-See-in-the-Dark]$ conda install pillow=8.0.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                            

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pillow=8.0.1 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=2.7.13

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.



(sid2) [ir967@log-1 Learning-to-See-in-the-Dark]$ conda install pillow=6.2.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /scratch/ir967/miniconda3/envs/sid2

  added / updated specs:
    - pillow=6.2.1


The following NEW packages will be INSTALLED:

  freetype           pkgs/main/linux-64::freetype-2.10.4-h5ab3b9f_0
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libtiff            pkgs/main/linux-64::libtiff-4.1.0-h2733197_1
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.2-heb0550a_3
  olefile            pkgs/main/linux-64::olefile-0.46-py27_0
  pillow             pkgs/main/linux-64::pillow-6.2.1-py27h34e0f95_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zstd               pkgs/main/linux-64::zstd-1.4.5-h9ceee32_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(sid2) [ir967@log-1 Learning-to-See-in-the-Dark]$ srun -c1 --gres=gpu:1 -t0:10:00 --mem=3000  --pty /bin/bash
(base) [ir967@gpu-40 Learning-to-See-in-the-Dark]$ conda activate sid2
(sid2) [ir967@gpu-40 Learning-to-See-in-the-Dark]$ python train_Sony.py 
2020-11-08 02:30:06.001379: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-11-08 02:30:06.148737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:04:00.0
totalMemory: 22.38GiB freeMemory: 22.23GiB
2020-11-08 02:30:06.148890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2020-11-08 02:30:43.229057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-08 02:30:43.229173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2020-11-08 02:30:43.229208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2020-11-08 02:30:43.229336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21562 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:04:00.0, compute capability: 6.1)
loaded ./e1_result_Sony/model.ckpt
1 1 Loss=0.095 Time=5.642
1 2 Loss=0.185 Time=2.506
1 3 Loss=0.147 Time=2.481
1 4 Loss=0.180 Time=2.316
1 5 Loss=0.167 Time=2.312
3 1 Loss=0.160 Time=0.109
3 2 Loss=0.173 Time=0.085
3 3 Loss=0.164 Time=0.087
3 4 Loss=0.171 Time=0.108
3 5 Loss=0.167 Time=0.092
5 1 Loss=0.159 Time=0.085
5 2 Loss=0.151 Time=0.113
5 3 Loss=0.157 Time=0.088
5 4 Loss=0.142 Time=2.240
5 5 Loss=0.130 Time=0.113
7 1 Loss=0.132 Time=2.202
7 2 Loss=0.128 Time=0.108
7 3 Loss=0.135 Time=0.085
7 4 Loss=0.144 Time=0.110
7 5 Loss=0.150 Time=0.085
8 1 Loss=0.149 Time=0.098
8 2 Loss=0.144 Time=0.112
8 3 Loss=0.134 Time=0.108
8 4 Loss=0.124 Time=0.108
8 5 Loss=0.103 Time=0.087
9 1 Loss=0.098 Time=0.109
9 2 Loss=0.104 Time=0.084
9 3 Loss=0.103 Time=2.233
9 4 Loss=0.107 Time=0.106
9 5 Loss=0.110 Time=0.111
10 1 Loss=0.113 Time=0.106
10 2 Loss=0.109 Time=0.109
10 3 Loss=0.106 Time=0.109
10 4 Loss=0.097 Time=0.087
10 5 Loss=0.090 Time=0.093
11 1 Loss=0.090 Time=0.106
11 2 Loss=0.090 Time=0.093
11 3 Loss=0.090 Time=0.111
11 4 Loss=0.092 Time=0.085
11 5 Loss=0.081 Time=0.105
12 1 Loss=0.085 Time=0.085
12 2 Loss=0.084 Time=0.109
12 3 Loss=0.095 Time=0.096
12 4 Loss=0.099 Time=0.085
12 5 Loss=0.097 Time=0.108
162 1 Loss=0.045 Time=0.085
162 2 Loss=0.043 Time=0.084
162 3 Loss=0.043 Time=0.110
162 4 Loss=0.043 Time=0.085
162 5 Loss=0.044 Time=0.088
163 1 Loss=0.042 Time=0.094
163 2 Loss=0.043 Time=0.094
163 3 Loss=0.044 Time=0.109
163 4 Loss=0.042 Time=0.106
163 5 Loss=0.041 Time=0.092
164 1 Loss=0.042 Time=0.092
164 2 Loss=0.045 Time=0.095
164 3 Loss=0.045 Time=0.086
164 4 Loss=0.047 Time=0.093
164 5 Loss=0.049 Time=0.093
165 1 Loss=0.049 Time=0.106
165 2 Loss=0.049 Time=0.092
165 3 Loss=0.049 Time=0.107
165 4 Loss=0.050 Time=0.106
165 5 Loss=0.047 Time=0.084
^CTraceback (most recent call last):


(sid2) [ir967@gpu-40 Learning-to-See-in-the-Dark]$ vi train_Sony.py 
(sid2) [ir967@gpu-40 Learning-to-See-in-the-Dark]$ python train_Sony.py 
2020-11-08 02:37:26.765039: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-11-08 02:37:26.924175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:04:00.0
totalMemory: 22.38GiB freeMemory: 22.23GiB
2020-11-08 02:37:26.924348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2020-11-08 02:37:52.317697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-08 02:37:52.317827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2020-11-08 02:37:52.317856: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2020-11-08 02:37:52.317978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21562 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:04:00.0, compute capability: 6.1)
loaded ./e1_result_Sony/model.ckpt
Killed
(sid2) [ir967@gpu-40 Learning-to-See-in-the-Dark]$ srun: Force Terminated job 13578123
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: gpu-40: task 0: Out Of Memory
srun: Terminating job step 13578123.0
(sid2) [ir967@log-1 Learning-to-See-in-the-Dark]$ exit
logout
Connection to localhost closed.
Ilyeechs-MacBook-Pro:~ ilyeech$ 
